export const stripeConfig = {
  products: [
    {
      priceId: "price_1RqKi8A45RYvGvTv9y9KxiAC",
      productId: "prod_SlsTJiHTY3Zn8Q",
      name: "plan_free", // translation key
      description: "plan_free_desc", // translation key
      mode: "subscription" as const,
      price: 0,
      interval: "month" as const,
      features: [
        "plan_free_1",
        "plan_free_2",
        "plan_free_3",
        "plan_free_4",
        "plan_free_5",
      ],
      limits: {
        tokens_per_month: 20000,
        max_documents: 10,
        max_chatbots: 1,
        api_requests_per_minute: 10,
        emails_per_month: 50,
      },
      popular: false,
    },
    {
      priceId: "price_1RqKiBA45RYvGvTvPdcDD6oW",
      productId: "prod_SlsTe42lvztQOX",
      name: "plan_starter",
      description: "plan_starter_desc",
      mode: "subscription" as const,
      price: 19,
      interval: "month" as const,
      features: [
        "plan_starter_1",
        "plan_starter_2",
        "plan_starter_3",
        "plan_starter_4",
        "plan_starter_5",
      ],
      limits: {
        tokens_per_month: 200000,
        max_documents: 50,
        max_chatbots: 5,
        api_requests_per_minute: 50,
        emails_per_month: 200,
      },
      popular: true,
    },
    {
      priceId: "price_1RqKiDA45RYvGvTvOQjdblYC",
      productId: "prod_SlsT0nbJVgu1ym",
      name: "plan_growth",
      description: "plan_growth_desc",
      mode: "subscription" as const,
      price: 79,
      interval: "month" as const,
      features: [
        "plan_growth_1",
        "plan_growth_2",
        "plan_growth_3",
        "plan_growth_4",
        "plan_growth_5",
      ],
      limits: {
        tokens_per_month: 1000000,
        max_documents: 250,
        max_chatbots: 25,
        api_requests_per_minute: 200,
        emails_per_month: 1000,
      },
      popular: false,
    },
    {
      priceId: "price_1RqKiGA45RYvGvTv8RfZCW3V",
      productId: "prod_SlsTyKCMAL8Wbb",
      name: "plan_business",
      description: "plan_business_desc",
      mode: "subscription" as const,
      price: 249,
      interval: "month" as const,
      features: [
        "plan_business_1",
        "plan_business_2",
        "plan_business_3",
        "plan_business_4",
        "plan_business_5",
      ],
      limits: {
        tokens_per_month: 5000000,
        max_documents: 1000,
        max_chatbots: 100,
        api_requests_per_minute: 1000,
        emails_per_month: 5000,
      },
      popular: false,
    },
  ],
};

export default stripeConfig;
